/**
 * @file rolePermissionMap.js
 * @description Role to Capability Permission Mappings.
 */

import { ROLES } from "./roleDefinitions.js";
import { PERMISSIONS } from "./permissionDefinitions.js";

export const USER_PERMISSIONS = [
  PERMISSIONS.USE_AI_ASSISTANT,
  PERMISSIONS.ACCESS_CODING_STUDIO,
  PERMISSIONS.EXECUTE_TERMINAL,
  PERMISSIONS.MODIFY_WORKSPACE,
  PERMISSIONS.ACCESS_KNOWLEDGE,
  PERMISSIONS.MANAGE_KNOWLEDGE,
  PERMISSIONS.CREATE_PROJECT,
  PERMISSIONS.MODIFY_PROJECT,
  PERMISSIONS.DELETE_PROJECT,
  PERMISSIONS.ACCESS_PLANNER,
  PERMISSIONS.MANAGE_TASKS,
  PERMISSIONS.ACCESS_NOTES,
  PERMISSIONS.MANAGE_NOTES,
  PERMISSIONS.RUN_AGENT,
  PERMISSIONS.APPROVE_AGENT_ACTIONS,
  PERMISSIONS.EXECUTE_AGENT_COMMANDS,
  PERMISSIONS.CONNECT_GITHUB,
  PERMISSIONS.READ_REPOSITORY,
  PERMISSIONS.READ_REMOTE_REPOSITORY,
  PERMISSIONS.READ_GITHUB_ISSUES,
  PERMISSIONS.READ_GITHUB_PULL_REQUESTS,
  PERMISSIONS.CREATE_BRANCH,
  PERMISSIONS.SWITCH_BRANCH,
  PERMISSIONS.CREATE_COMMIT,
  PERMISSIONS.PUSH_REPOSITORY,
  PERMISSIONS.PREPARE_PULL_REQUEST,
  PERMISSIONS.ACCESS_RUNTIME,
  PERMISSIONS.EXECUTE_RUNTIME_TOOLS,
];

export const ADMIN_PERMISSIONS = [
  ...USER_PERMISSIONS,
  PERMISSIONS.CREATE_PULL_REQUEST,
  PERMISSIONS.ACCESS_ADMIN,
  PERMISSIONS.MANAGE_USERS,
  PERMISSIONS.MANAGE_ROLES,
  PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
  PERMISSIONS.VIEW_AUDIT_LOGS,
  PERMISSIONS.MANAGE_INTEGRATIONS,
  PERMISSIONS.MANAGE_RUNTIME_CONFIGURATION,
];

export const ROLE_PERMISSION_MAP = {
  [ROLES.USER]: new Set(USER_PERMISSIONS),
  [ROLES.ADMIN]: new Set(ADMIN_PERMISSIONS),
};

/**
 * Get permission list for a role
 * @param {string} role
 * @returns {Array<string>}
 */
export function getPermissionsForRole(role = ROLES.USER) {
  const normalized = String(role).toUpperCase();
  if (normalized === "ADMIN") return [...ADMIN_PERMISSIONS];
  return [...USER_PERMISSIONS];
}

export default ROLE_PERMISSION_MAP;
