/**
 * @file prPreparer.js
 * @description Pull Request Preparer & Formatter for AI Engineer OS V1.6.
 * Generates PR title, summary, implementation details, testing results, and risks for explicit user approval.
 */

export function preparePullRequestData({
  task,
  branch,
  diff,
  testResults,
  buildResult,
  codeReview,
}) {
  const title = `feat: ${task?.title || "Update repository implementation"}`;

  const body = `## Summary
${task?.problemStatement || "Autonomous engineering task execution completed by AI Engineer OS."}

## Proposed Changes
${(task?.affectedFiles || []).map((f) => `- \`${f}\``).join("\n") || "- Updated files"}

## Testing Performed
- **Targeted Tests**: ${testResults?.passed ? "PASS" : "FAIL"} (${testResults?.summary || "node --test runtime/tests/health.test.js"})
- **Production Build**: ${buildResult?.passed ? "PASS" : "FAIL"} (\`npm run build\`)

## Code Review & Safety Verification
- **Code Review Status**: ${codeReview?.passed ? "APPROVED" : "BLOCK"}
- **Critical Findings**: ${codeReview?.criticalCount || 0}
- **High Findings**: ${codeReview?.highCount || 0}
- **Secret Scan**: PASSED (No API keys or credentials detected)

## Risks & Considerations
${(task?.riskAssessment || ["Low risk change"]).map((r) => `- ${r}`).join("\n")}

---
*Generated by AI Engineer OS V1.6 — Git Engineering Workflow*`;

  return {
    title,
    body,
    head: branch || "feature/ai-engineer-os-health-endpoint",
    base: "main",
  };
}

export default preparePullRequestData;
